#goapp

version: '3.4'
services:
  goapp:
    entrypoint: /bin/bash
    build:
      context: .
      dockerfile: Dockerfile
    command:  -c "tail -f /dev/null"
    user: root
    volumes:
      - ./:/go/src/goapp
