#goapp

version: '3.4'
services:
  nodeapp:
    entrypoint: /bin/bash
    ports:
      - "3000:3000" # map the pors you need
    build:
      context: .
      dockerfile: Dockerfile
    command:  -c "tail -f /dev/null"
    user: root
    volumes:
      - ./:/code
